### ISSUE TITLE
Source for conversion

### ISSUE THREAD

**Issue by simon-rob** [Livox-SDK/Tools#1]
Do you have any plans to release the source of this conversion tool?

**Comment by simon-rob** [comment]
Any updates on the source.. I am trying to work out if the reflectivity is mapped to the RGB colors by the utility as I seem to get just monochrome.

**Comment by simon-rob** [comment]
Yes they are mapped.

**Comment by Livox-SDK** [comment]
The format of lvx file will open to all users later. We are preparing the docs of lvx. You can convert lvx to other format as you want.

**Comment by longhui238** [comment]
The format of lvx file is released. [link](https://www.livoxtech.com/3296f540ecf5458a8829e01cf429798e/downloads/20190225/Lvx%20Specifications_EN.pdf)
