### ISSUE TITLE
batch conversion of .lvx files

### ISSUE THREAD

**Issue by cfessler** [Livox-SDK/Tools#9]
i would like to ask if there is a way to batch-convert a complete folder to .las

i am using it to capture a steady scene, so merging all frames of the .lvx to .las would be enough, even I would appreciate the conversion of non-steady scenes to pointclouds like the loam does.

**Comment by Livox-SDK** [comment]
Hi cfessler,
I am sorry to say that we don't have such a program to batch coveting multiple lvx files.
